-- GGC Weapons Pack - Weapon Definitions
-- These will be loaded by mythic-inventory
_itemsSource = _itemsSource or {}

_itemsSource['weapons_ggc'] = {
	-- ========================
	-- MELEE WEAPONS (5)
	-- ========================
	{
		name = 'WEAPON_KATANA',
		label = 'Katana',
		ammoType = nil,
		requiresLicense = false,
		price = 5000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 60), -- 60 days
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 30,
		gun = false,
	},
	{
		name = 'WEAPON_SHIV',
		label = 'Shiv',
		ammoType = nil,
		requiresLicense = false,
		price = 500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 14), -- 14 days
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 5,
		gun = false,
	},
	{
		name = 'WEAPON_SLEDGEHAMMER',
		label = 'Sledge Hammer',
		ammoType = nil,
		requiresLicense = false,
		price = 2000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 90), -- 90 days
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 50,
		gun = false,
	},
	{
		name = 'WEAPON_KARAMBIT',
		label = 'Karambit',
		ammoType = nil,
		requiresLicense = false,
		price = 3000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 60), -- 60 days
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 8,
		gun = false,
	},
	{
		name = 'WEAPON_KEYBOARD',
		label = 'Keyboard',
		ammoType = nil,
		requiresLicense = false,
		price = 100,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7), -- 7 days
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 12,
		gun = false,
	},

	-- ========================
	-- LESS LETHAL (1)
	-- ========================
	{
		name = 'WEAPON_BEANBAG',
		label = 'Bean Bag Shotgun',
		ammoType = 'AMMO_SHOTGUN',
		requiresLicense = true,
		bulletCount = 8,
		price = 8000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42), -- 42 days
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 35,
		gun = true,
	},

	-- ========================
	-- HANDGUNS (9)
	-- ========================
	{
		name = 'WEAPON_GLOCK17',
		label = 'Glock-17',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		bulletCount = 17,
		price = 3500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42), -- 42 days
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_GLOCK18C',
		label = 'Glock-18C',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		bulletCount = 17,
		price = 4500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42), -- 42 days
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_GLOCK22',
		label = 'Glock-22',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		bulletCount = 15,
		price = 3800,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42), -- 42 days
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = 'WEAPON_DEAGLE',
		label = 'Desert Eagle',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		bulletCount = 7,
		price = 8000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42), -- 42 days
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 20,
		gun = true,
	},
	{
		name = 'WEAPON_FNX45',
		label = 'FN FNX45',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		bulletCount = 15,
		price = 4200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42), -- 42 days
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
	{
		name = 'WEAPON_M1911',
		label = 'M1911',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		bulletCount = 7,
		price = 3800,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42), -- 42 days
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
	{
		name = 'WEAPON_GLOCK20',
		label = 'Glock-20',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		bulletCount = 15,
		price = 4000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42), -- 42 days
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 11,
		gun = true,
	},
	{
		name = 'WEAPON_GLOCK19GEN4',
		label = 'Glock-19 Gen 4',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		bulletCount = 15,
		price = 3600,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42), -- 42 days
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 9,
		gun = true,
	},
	{
		name = 'WEAPON_BROWNING',
		label = 'Browning Hi-Power',
		ammoType = 'AMMO_PISTOL',
		requiresLicense = true,
		bulletCount = 13,
		price = 3500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42), -- 42 days
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},

	-- ========================
	-- SMGs (2)
	-- ========================
	{
		name = 'WEAPON_PMXFM',
		label = 'Beretta PMX',
		ammoType = 'AMMO_SMG',
		requiresLicense = true,
		bulletCount = 30,
		price = 12000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42), -- 42 days
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 30,
		gun = true,
	},
	{
		name = 'WEAPON_MAC10',
		label = 'MAC-10',
		ammoType = 'AMMO_SMG',
		requiresLicense = true,
		bulletCount = 32,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42), -- 42 days
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 25,
		gun = true,
	},

	-- ========================
	-- RIFLES (8)
	-- ========================
	{
		name = 'WEAPON_MK47FM',
		label = 'Mk47 Mutant',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		bulletCount = 30,
		price = 18000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42), -- 42 days
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 40,
		gun = true,
	},
	{
		name = 'WEAPON_M6IC',
		label = 'LWRC M6IC',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		bulletCount = 30,
		price = 16000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42), -- 42 days
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 35,
		gun = true,
	},
	{
		name = 'WEAPON_SCARSC',
		label = 'SCAR SC',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		bulletCount = 30,
		price = 17000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42), -- 42 days
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 38,
		gun = true,
	},
	{
		name = 'WEAPON_M4',
		label = 'M4A1 Carbine',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		bulletCount = 30,
		price = 15000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42), -- 42 days
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 35,
		gun = true,
	},
	{
		name = 'WEAPON_AK47',
		label = 'AK-47',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		bulletCount = 30,
		price = 16000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42), -- 42 days
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 43,
		gun = true,
	},
	{
		name = 'WEAPON_AK74',
		label = 'AK-74',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		bulletCount = 30,
		price = 15000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42), -- 42 days
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 39,
		gun = true,
	},
	{
		name = 'WEAPON_AKS74',
		label = 'AKS-74',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		bulletCount = 30,
		price = 14500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42), -- 42 days
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 37,
		gun = true,
	},
	{
		name = 'WEAPON_GROZA',
		label = 'OTs-14 Groza',
		ammoType = 'AMMO_RIFLE',
		requiresLicense = true,
		bulletCount = 20,
		price = 19000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 42), -- 42 days
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 42,
		gun = true,
	},
}
